[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stitcher-application"
version = "0.1.0"
description = "Orchestration layer for Stitcher."
requires-python = ">=3.10"
dependencies = [
    "stitcher-spec",
    "stitcher-common",
    "stitcher-config",
    "stitcher-python-adapter",
    "stitcher-stubgen",
    "stitcher-workspace",
    "stitcher-index",
    "pyneedle",
]

[tool.hatch.build.targets.wheel]
packages = ["src/stitcher"]

[tool.uv.sources]
stitcher-spec = { workspace = true }
stitcher-common = { workspace = true }
stitcher-config = { workspace = true }
stitcher-python-adapter = { workspace = true }
stitcher-stubgen = { workspace = true }
stitcher-workspace = { workspace = true }
stitcher-index = { workspace = true }
pyneedle = { workspace = true }