[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stitcher-stubgen"
version = "0.1.0"
description = "Specialized stub generation engine for Stitcher."
requires-python = ">=3.10"
dependencies = [
    "stitcher-spec",
    "stitcher-common",
    "stitcher-workspace",
]

[tool.hatch.build.targets.wheel]
packages = ["src/stitcher"]

[tool.uv.sources]
stitcher-spec = { workspace = true }
stitcher-common = { workspace = true }
stitcher-workspace = { workspace = true }
stitcher-test-utils = { workspace = true }