[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "pyneedle-stubs"
version = "0.1.0"
description = "PEP 561 type stubs for pyneedle"

[tool.hatch.build.targets.wheel]
packages = [
    "src/pyneedle",
]
