[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stitcher-test-utils"
version = "0.1.0"
description = "Internal testing utilities for the Stitcher project."
requires-python = ">=3.10"
dependencies = [
    "pyneedle",
    "PyYAML",
    "tomli-w",
    "stitcher-application",
    "stitcher-python-adapter",
    "stitcher-index",
    "stitcher-workspace",
]

[tool.hatch.build.targets.wheel]
packages = ["src/stitcher"]

[tool.uv.sources]
pyneedle = { workspace = true }
stitcher-application = { workspace = true }
stitcher-python-adapter = { workspace = true }
stitcher-workspace = { workspace = true }