[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stitcher-spec"
version = "0.1.0"
description = "Intermediate Representation (IR) models for Stitcher."
requires-python = ">=3.10"
dependencies = [
    "pyneedle-pointer",
]

[tool.hatch.build.targets.wheel]
packages = ["src/stitcher"]

[tool.uv.sources]
pyneedle-pointer = { workspace = true }