[project]
name = "stitcher-python"
version = "0.1.0"
description = "Stitching the gap between dynamic code and static analysis."
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "mypy",
    "stitcher-cli",
    "stitcher-application",
    "stitcher-needle",
    "stitcher-test-utils",
]

[tool.uv.workspace]
members = ["packages/*", "packages/stitcher-test-utils"]

[tool.uv.sources]
stitcher-spec = { workspace = true }
stitcher-common = { workspace = true }
stitcher-scanner = { workspace = true }
stitcher-io = { workspace = true }
stitcher-config = { workspace = true }
stitcher-application = { workspace = true }
stitcher-cli = { workspace = true }
stitcher-needle = { workspace = true }
stitcher-test-utils = { workspace = true }

[tool.pytest.ini_options]
addopts = "-ra --cov=stitcher --cov=needle --cov-report=term-missing"
testpaths = ["tests", "packages"]
norecursedirs = ["tests/fixtures"]
pythonpath = [
    "packages/stitcher-spec/src", 
    "packages/stitcher-common/src", 
    "packages/stitcher-scanner/src", 
    "packages/stitcher-io/src", 
    "packages/stitcher-config/src", 
    "packages/stitcher-application/src", 
    "packages/stitcher-cli/src", 
    "packages/stitcher-needle/src",
    "packages/pyneedle-spec/src",
    "packages/pyneedle-pointer/src",
    "packages/pyneedle-nexus/src",
    "packages/pyneedle/src"
]

[tool.stitcher]
scan_paths = ["packages"]

[tool.pyright]
include = ["packages", "tests"]
# 显式告知 IDE 所有子包的源码位置，解决 Monorepo 解析问题
extraPaths = [
    "packages/stitcher-spec/src",
    "packages/stitcher-common/src",
    "packages/stitcher-scanner/src",
    "packages/stitcher-io/src",
    "packages/stitcher-config/src",
    "packages/stitcher-application/src",
    "packages/stitcher-cli/src",
    "packages/stitcher-needle/src",
    "packages/stitcher-test-utils/src",
]
