[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyneedle-spec"
version = "0.1.0"
description = "Core protocols and specifications for the PyNeedle ecosystem."
requires-python = ">=3.10"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/needle"]