[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "stitcher-python-stubs"
version = "0.1.0"
description = "PEP 561 type stubs for stitcher-python"

[tool.hatch.build.targets.wheel]
packages = [
    "src/stitcher",
]
