[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stitcher-bus"
version = "0.1.0"
description = "Event and message orchestration for Stitcher."
requires-python = ">=3.10"
dependencies = [
    "pyneedle-pointer ~= 0.1.0",
    "pyneedle-spec ~= 0.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/stitcher"]
include = ["/src/stitcher/bus/assets"]
